image: node:8.9

stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$9f0c42bc-3d10-4cee-8ace-a8ada01bbc29@git.heroku.com/noticer-dev.git
    - git push heroku master
    - echo "Deployed to production server"
  environment:
  when: manual
  only:
    - dev_v2
