image: node:8.9

stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/noticer-gitlab.git
    - git push heroku master
    - echo "Deployed to production server"
  environment:
  when: manual
  only:
    - master
