image: node:8.9

stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$9f0c42bc-3d10-4cee-8ace-a8ada01bbc29@git.heroku.com/testnoticer.git
    - git push https://heroku:9f0c42bc-3d10-4cee-8ace-a8ada01bbc29@git.heroku.com/testnoticer.git HEAD:master
  environment:
  when: manual
  only:
    - dev_v2
