image: node:8.9

stages:
  - deploy

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$c636d7d5-daf9-4c10-a934-4c43d11c693b@git.heroku.com/noticer-dev.git
    - git push https://heroku:c636d7d5-daf9-4c10-a934-4c43d11c693b@git.heroku.com/noticer-dev.git HEAD:refs/heads/master
  environment:
  when: manual
  only:
    - dev_v2
